name: modern_dashboard
description: A modern dashboard application
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  shared_preferences: ^2.1.1
  http: ^1.0.0
  web_socket_channel: ^2.4.0
  flutter_staggered_grid_view: ^0.6.2
  glassmorphism: ^3.0.0
  cached_network_image: ^3.2.3
  video_player: ^2.6.1
  flutter_animate: ^4.2.0
  provider: ^6.0.5
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  cloud_functions: ^4.7.6
  crypto: ^3.0.3
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
