// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUouZDuLrmsJcAqAdeTr7b6XYmT8KLkKE',
    appId: '1:965908404542:web:126887b90ad4df7452f46f',
    messagingSenderId: '965908404542',
    projectId: 'moderndashboard-68352',
    authDomain: 'moderndashboard-68352.firebaseapp.com',
    storageBucket: 'moderndashboard-68352.firebasestorage.app',
    measurementId: 'G-8VMCJEM29M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8K9mF2nP7qR5sT1uV3wX0yZ2a4bC6dE8',
    appId: '1:965908404542:android:8f7e6d5c4b3a29182736f4e',
    messagingSenderId: '965908404542',
    projectId: 'moderndashboard-68352',
    storageBucket: 'moderndashboard-68352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9L0nO3pQ6rS8tU2vW4xY1zA3bCd7eF9',
    appId: '1:965908404542:ios:9g8f7e6d5c4b3a291827e5f',
    messagingSenderId: '965908404542',
    projectId: 'moderndashboard-68352',
    storageBucket: 'moderndashboard-68352.firebasestorage.app',
    iosBundleId: 'com.example.modernDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA93Y6ChDQMbVserp7PEbmdZXO6mphppt4',
    appId: '1:965908404542:ios:3a9ef7337e18c0f152f46f',
    messagingSenderId: '965908404542',
    projectId: 'moderndashboard-68352',
    storageBucket: 'moderndashboard-68352.firebasestorage.app',
    iosBundleId: 'com.example.modernDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyE0M1nP4qR7sU9vW5xY2zA4bCd8eF0gH2',
    appId: '1:965908404542:web:0h9g8f7e6d5c4b3a2918f6g',
    messagingSenderId: '965908404542',
    projectId: 'moderndashboard-68352',
    authDomain: 'moderndashboard-68352.firebaseapp.com',
    storageBucket: 'moderndashboard-68352.firebasestorage.app',
    measurementId: 'G-9WNDJFM30N',
  );
}