// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUouZDuLrmsJcAqAdeTr7b6XYmT8KLkKE',
    appId: '1:965908404542:web:126887b90ad4df7452f46f',
    messagingSenderId: '965908404542',
    projectId: 'moderndashboard-68352',
    authDomain: 'moderndashboard-68352.firebaseapp.com',
    storageBucket: 'moderndashboard-68352.firebasestorage.app',
    measurementId: 'G-8VMCJEM29M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
    appId: '1:123456789012:android:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'modern-dashboard-demo',
    storageBucket: 'modern-dashboard-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'modern-dashboard-demo',
    storageBucket: 'modern-dashboard-demo.appspot.com',
    iosBundleId: 'com.example.modernDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA93Y6ChDQMbVserp7PEbmdZXO6mphppt4',
    appId: '1:965908404542:ios:3a9ef7337e18c0f152f46f',
    messagingSenderId: '965908404542',
    projectId: 'moderndashboard-68352',
    storageBucket: 'moderndashboard-68352.firebasestorage.app',
    iosBundleId: 'com.example.modernDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'modern-dashboard-demo',
    authDomain: 'modern-dashboard-demo.firebaseapp.com',
    storageBucket: 'modern-dashboard-demo.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}