name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  cpp-backend:
    runs-on: self-hosted
    name: Build C++ Backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libcurl4-openssl-dev nlohmann-json3-dev jq \
          libsqlite3-dev libxml2-dev pkg-config libtinyxml2-dev
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Test build artifacts
      run: |
        ls -la build/
        if [ -f "build/ModernDashboard" ]; then
          echo "✅ C++ backend built successfully"
        else
          echo "❌ C++ backend build failed"
          exit 1
        fi

  flutter-frontend:
    runs-on: self-hosted
    name: Build Flutter Frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Get Flutter dependencies
      working-directory: flutter_frontend
      run: flutter pub get
    
    - name: Analyze Flutter code
      working-directory: flutter_frontend
      run: flutter analyze
    
    - name: Build Flutter web
      working-directory: flutter_frontend
      run: flutter build web --no-tree-shake-icons
    
    # Linux build removed - focusing on web and native builds per requirements
    
    - name: Test build artifacts
      working-directory: flutter_frontend
      run: |
        echo "Checking build artifacts..."
        echo "Web build:"
        ls -la build/web/ || echo "No web build found"
        if [ -f "build/web/index.html" ]; then
          echo "✅ Flutter web built successfully"
        else
          echo "❌ Flutter web build failed"
          exit 1
        fi


  integration-test:
    runs-on: self-hosted
    name: Integration Test (Linux)
    needs: [cpp-backend, flutter-frontend]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libcurl4-openssl-dev nlohmann-json3-dev jq \
          libsqlite3-dev libxml2-dev pkg-config libtinyxml2-dev \
          clang ninja-build libgtk-3-dev liblzma-dev
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Build C++ Backend
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
    
    - name: Build Flutter Frontend
      working-directory: flutter_frontend
      run: |
        flutter pub get
        flutter build web --no-tree-shake-icons
        flutter build linux --debug
    
    - name: Verify integration
      run: |
        echo "Checking build artifacts..."
        echo "C++ Backend:"
        ls -la build/
        echo "Flutter Web:"
        ls -la flutter_frontend/build/web/
        echo "Flutter Linux:"
        ls -la flutter_frontend/build/linux/x64/debug/bundle/
        
        if [ -f "build/ModernDashboard" ] && [ -f "build/libmoderndash.so" ]; then
          echo "✅ C++ backend built successfully"
        else
          echo "❌ C++ backend build failed"
          exit 1
        fi
        
        if [ -f "flutter_frontend/build/web/index.html" ]; then
          echo "✅ Flutter web built successfully"  
        else
          echo "❌ Flutter web build failed"
          exit 1
        fi
        
        if [ -f "flutter_frontend/build/linux/x64/debug/bundle/modern_dashboard" ]; then
          echo "✅ Flutter Linux built successfully"
        else
          echo "❌ Flutter Linux build failed"
          exit 1
        fi
        
        echo "🎉 All builds completed successfully!"

